import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const canadianSchools = [
  // Top Universities
  {
    name: "University of Toronto",
    type: "university",
    province: "Ontario",
    city: "Toronto",
    website: "https://www.utoronto.ca",
    ranking: 21,
    established: 1827,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 58160,
    tuitionMasters: 25000,
    tuitionPhd: 22000,
    applicationFee: 155,
    description: "Canada's leading research university, ranked #1 in Canada. Known for excellence in engineering, computer science, business, and medicine.",
  },
  {
    name: "University of British Columbia",
    type: "university",
    province: "British Columbia",
    city: "Vancouver",
    website: "https://www.ubc.ca",
    ranking: 34,
    established: 1908,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 42802,
    tuitionMasters: 23000,
    tuitionPhd: 20000,
    applicationFee: 125,
    description: "Top-tier research university on Canada's west coast. Beautiful campus, strong programs in sciences, business, and arts.",
  },
  {
    name: "McGill University",
    type: "university",
    province: "Quebec",
    city: "Montreal",
    website: "https://www.mcgill.ca",
    ranking: 31,
    established: 1821,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 32141,
    tuitionMasters: 20000,
    tuitionPhd: 18000,
    applicationFee: 110,
    description: "World-renowned research university in Montreal. Known for medicine, law, engineering, and sciences.",
  },
  {
    name: "McMaster University",
    type: "university",
    province: "Ontario",
    city: "Hamilton",
    website: "https://www.mcmaster.ca",
    ranking: 152,
    established: 1887,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 35500,
    tuitionMasters: 22000,
    tuitionPhd: 19000,
    applicationFee: 150,
    description: "Leading research-intensive university. Home to Canada's only medical school with problem-based learning curriculum.",
  },
  {
    name: "University of Alberta",
    type: "university",
    province: "Alberta",
    city: "Edmonton",
    website: "https://www.ualberta.ca",
    ranking: 110,
    established: 1908,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 28800,
    tuitionMasters: 18500,
    tuitionPhd: 16000,
    applicationFee: 125,
    description: "Top 5 Canadian research university. Strong in engineering, sciences, business, and health sciences.",
  },
  {
    name: "University of Montreal (Université de Montréal)",
    type: "university",
    province: "Quebec",
    city: "Montreal",
    website: "https://www.umontreal.ca",
    ranking: 141,
    established: 1878,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 28000,
    tuitionMasters: 17000,
    tuitionPhd: 15000,
    applicationFee: 100,
    description: "Leading French-language university. Excellent programs in health sciences, law, and social sciences.",
  },
  {
    name: "University of Waterloo",
    type: "university",
    province: "Ontario",
    city: "Waterloo",
    website: "https://uwaterloo.ca",
    ranking: 112,
    established: 1957,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 47000,
    tuitionMasters: 24000,
    tuitionPhd: 21000,
    applicationFee: 145,
    description: "Canada's most innovative university. World-renowned co-op program, top computer science and engineering.",
  },
  {
    name: "Western University",
    type: "university",
    province: "Ontario",
    city: "London",
    website: "https://www.uwo.ca",
    ranking: 172,
    established: 1878,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 38000,
    tuitionMasters: 21000,
    tuitionPhd: 18000,
    applicationFee: 150,
    description: "Research-intensive university with strong business school (Ivey). Beautiful campus and vibrant student life.",
  },
  {
    name: "Queen's University",
    type: "university",
    province: "Ontario",
    city: "Kingston",
    website: "https://www.queensu.ca",
    ranking: 209,
    established: 1841,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 46000,
    tuitionMasters: 23000,
    tuitionPhd: 20000,
    applicationFee: 155,
    description: "Historic university with strong engineering, business, and health sciences programs. Close-knit community.",
  },
  {
    name: "University of Calgary",
    type: "university",
    province: "Alberta",
    city: "Calgary",
    website: "https://www.ucalgary.ca",
    ranking: 242,
    established: 1966,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 27000,
    tuitionMasters: 17500,
    tuitionPhd: 15000,
    applicationFee: 125,
    description: "Dynamic research university in Canada's energy capital. Strong in engineering, business, and health sciences.",
  },
  {
    name: "Trent University",
    type: "university",
    province: "Ontario",
    city: "Peterborough",
    website: "https://www.trentu.ca",
    ranking: 600,
    established: 1964,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 25000,
    tuitionMasters: 18000,
    tuitionPhd: 16000,
    applicationFee: 100,
    description: "Small, liberal arts-focused university with personalized education. Strong in environmental studies, psychology, and indigenous studies. Beautiful campus along the Otonabee River.",
  },
  {
    name: "Concordia University",
    type: "university",
    province: "Quebec",
    city: "Montreal",
    website: "https://www.concordia.ca",
    ranking: 521,
    established: 1974,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 30000,
    tuitionMasters: 19500,
    tuitionPhd: 17000,
    applicationFee: 120,
    description: "Dynamic, urban university in downtown Montreal. Known for innovative programs in fine arts, engineering, business (John Molson School), and computer science.",
  },

  // Top Colleges
  {
    name: "Seneca College",
    type: "college",
    province: "Ontario",
    city: "Toronto",
    website: "https://www.senecacollege.ca",
    ranking: null,
    established: 1967,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 16500,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 100,
    description: "Largest college in Canada. Excellent programs in business, technology, aviation, and creative arts.",
  },
  {
    name: "George Brown College",
    type: "college",
    province: "Ontario",
    city: "Toronto",
    website: "https://www.georgebrown.ca",
    ranking: null,
    established: 1967,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 15500,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 95,
    description: "Downtown Toronto college with strong culinary, hospitality, health, and business programs. Great co-op opportunities.",
  },
  {
    name: "Humber College",
    type: "college",
    province: "Ontario",
    city: "Toronto",
    website: "https://humber.ca",
    ranking: null,
    established: 1967,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 16000,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 100,
    description: "Leading polytechnic institution. Excellent programs in media, business, technology, and health sciences.",
  },
  {
    name: "Centennial College",
    type: "college",
    province: "Ontario",
    city: "Toronto",
    website: "https://www.centennialcollege.ca",
    ranking: null,
    established: 1966,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 15800,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 95,
    description: "Ontario's first community college. Diverse student body, strong programs in engineering, business, and health.",
  },
  {
    name: "Conestoga College",
    type: "college",
    province: "Ontario",
    city: "Kitchener",
    website: "https://www.conestogac.on.ca",
    ranking: null,
    established: 1967,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 15200,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 100,
    description: "Ontario's fastest-growing college. Strong ties to local tech industry, excellent co-op programs.",
  },
  {
    name: "Sheridan College",
    type: "college",
    province: "Ontario",
    city: "Oakville",
    website: "https://www.sheridancollege.ca",
    ranking: null,
    established: 1967,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 16800,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 100,
    description: "World-renowned animation and design programs. Strong in creative arts, business, and technology.",
  },
  {
    name: "Algonquin College",
    type: "college",
    province: "Ontario",
    city: "Ottawa",
    website: "https://www.algonquincollege.com",
    ranking: null,
    established: 1967,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 15000,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 95,
    description: "Ottawa's largest college. Strong programs in technology, health, business, and media.",
  },
  {
    name: "BCIT (British Columbia Institute of Technology)",
    type: "polytechnic",
    province: "British Columbia",
    city: "Burnaby",
    website: "https://www.bcit.ca",
    ranking: null,
    established: 1964,
    international: true,
    undergraduate: true,
    masters: true,
    phd: false,
    tuitionUndergrad: 18500,
    tuitionMasters: 25000,
    tuitionPhd: null,
    applicationFee: 120,
    description: "Leading polytechnic in Western Canada. Hands-on learning, strong industry connections, excellent job placement.",
  },
  {
    name: "Fanshawe College",
    type: "college",
    province: "Ontario",
    city: "London",
    website: "https://www.fanshawec.ca",
    ranking: null,
    established: 1967,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 15300,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 100,
    description: "One of Ontario's largest colleges. Strong programs in business, technology, health, and hospitality.",
  },
  {
    name: "Mohawk College",
    type: "college",
    province: "Ontario",
    city: "Hamilton",
    website: "https://www.mohawkcollege.ca",
    ranking: null,
    established: 1967,
    international: true,
    undergraduate: true,
    masters: false,
    phd: false,
    tuitionUndergrad: 15500,
    tuitionMasters: null,
    tuitionPhd: null,
    applicationFee: 95,
    description: "Hamilton's leading college. Excellent programs in health, skilled trades, business, and technology.",
  },

  // More Top Universities
  {
    name: "Simon Fraser University",
    type: "university",
    province: "British Columbia",
    city: "Burnaby",
    website: "https://www.sfu.ca",
    ranking: 318,
    established: 1965,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 32000,
    tuitionMasters: 19000,
    tuitionPhd: 16000,
    applicationFee: 125,
    description: "Top comprehensive university in BC. Strong in computing science, business, and communication.",
  },
  {
    name: "Dalhousie University",
    type: "university",
    province: "Nova Scotia",
    city: "Halifax",
    website: "https://www.dal.ca",
    ranking: 308,
    established: 1818,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 24000,
    tuitionMasters: 18000,
    tuitionPhd: 15000,
    applicationFee: 100,
    description: "Leading Atlantic Canadian university. Strong in health sciences, law, engineering, and marine research.",
  },
  {
    name: "University of Ottawa",
    type: "university",
    province: "Ontario",
    city: "Ottawa",
    website: "https://www.uottawa.ca",
    ranking: 237,
    established: 1848,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 36000,
    tuitionMasters: 20000,
    tuitionPhd: 17000,
    applicationFee: 110,
    description: "Canada's largest bilingual university. Located in the nation's capital. Strong in law, health, and public policy.",
  },
  {
    name: "York University",
    type: "university",
    province: "Ontario",
    city: "Toronto",
    website: "https://www.yorku.ca",
    ranking: 456,
    established: 1959,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 34000,
    tuitionMasters: 19500,
    tuitionPhd: 16500,
    applicationFee: 120,
    description: "Canada's third-largest university. Excellent business school (Schulich), strong in arts, law, and sciences.",
  },
  {
    name: "Carleton University",
    type: "university",
    province: "Ontario",
    city: "Ottawa",
    website: "https://carleton.ca",
    ranking: 601,
    established: 1942,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 32000,
    tuitionMasters: 18500,
    tuitionPhd: 15500,
    applicationFee: 110,
    description: "Innovative teaching and research. Top programs in journalism, public affairs, engineering, and computer science.",
  },
  {
    name: "Ryerson University (Toronto Metropolitan University)",
    type: "university",
    province: "Ontario",
    city: "Toronto",
    website: "https://www.torontomu.ca",
    ranking: 801,
    established: 1948,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 33000,
    tuitionMasters: 19000,
    tuitionPhd: 16000,
    applicationFee: 130,
    description: "Downtown Toronto university. Career-focused education with strong co-op. Excellent for business, media, and engineering.",
  },
  {
    name: "University of Victoria",
    type: "university",
    province: "British Columbia",
    city: "Victoria",
    website: "https://www.uvic.ca",
    ranking: 359,
    established: 1963,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 28500,
    tuitionMasters: 17500,
    tuitionPhd: 14500,
    applicationFee: 115,
    description: "Beautiful campus in BC's capital. Strong in environmental studies, engineering, business, and computer science.",
  },
  {
    name: "University of Saskatchewan",
    type: "university",
    province: "Saskatchewan",
    city: "Saskatoon",
    website: "https://www.usask.ca",
    ranking: 441,
    established: 1907,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 22000,
    tuitionMasters: 15000,
    tuitionPhd: 12500,
    applicationFee: 100,
    description: "Leading research university in Saskatchewan. Strong in agriculture, engineering, and health sciences.",
  },
  {
    name: "University of Manitoba",
    type: "university",
    province: "Manitoba",
    city: "Winnipeg",
    website: "https://umanitoba.ca",
    ranking: 651,
    established: 1877,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 20500,
    tuitionMasters: 14000,
    tuitionPhd: 11500,
    applicationFee: 100,
    description: "Western Canada's first university. Affordable tuition, strong in health sciences, engineering, and business.",
  },
  {
    name: "Memorial University of Newfoundland",
    type: "university",
    province: "Newfoundland and Labrador",
    city: "St. John's",
    website: "https://www.mun.ca",
    ranking: 701,
    established: 1925,
    international: true,
    undergraduate: true,
    masters: true,
    phd: true,
    tuitionUndergrad: 11460,
    tuitionMasters: 10000,
    tuitionPhd: 8500,
    applicationFee: 80,
    description: "Lowest tuition in Canada for international students. Beautiful coastal location. Strong in marine sciences and engineering.",
  },
]

async function seedSchools() {
  console.log('🌱 Starting to seed Canadian schools...')

  for (const school of canadianSchools) {
    const existing = await prisma.canadianSchool.findFirst({
      where: { name: school.name }
    })

    if (existing) {
      await prisma.canadianSchool.update({
        where: { id: existing.id },
        data: school,
      })
      console.log(`🔄 Updated: ${school.name}`)
    } else {
      await prisma.canadianSchool.create({
        data: school,
      })
      console.log(`✅ Created: ${school.name}`)
    }
  }

  console.log('🎉 Successfully seeded all Canadian schools!')

  const count = await prisma.canadianSchool.count()
  console.log(`📊 Total schools in database: ${count}`)
}

seedSchools()
  .catch((error) => {
    console.error('❌ Error seeding schools:', error)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
